### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by chiharukakimoto** [chiharukakimoto/furima-36185#21]
# URL
https://furima-36185.herokuapp.com/

Basic認証のIDとパスワード
admin
2222
出品者用のメールアドレスとパスワード 
メールアドレス名: qianchun@hotmail.co.jp
パスワード: chiharu0308

購入者用のメールアドレスとパスワード 
メールアドレス: 1qianchun@hotmail.co.jp
パスワード: chiharu0308

購入用カード情報
番号：4242424242424242
期限：Sat Jan 23 2021 00:00:00 GMT+0900 (JST)
セキュリティコード：123

**Comment by snkw-works** [comment]
@chiharukakimoto さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **ユーザー登録画面にて、エラーハンドリングの際、重複したエラーメッセージが表示されないよう修正しましょう**
「Password can't be blank」というメッセージが重複して表示されています。

- [ ] **ログイン状態の場合でも、売却済みの商品には、「商品の編集」「削除」「購入画面に進む」ボタンが表示されないよう修正しましょう**
売却済みの商品にも、「商品の編集」「削除」ボタンが表示されています。
<img width="1426" alt="スクリーンショット 2021-11-14 15 58 39" src="https://user-images.githubusercontent.com/54050089/141670924-9accb5a8-2d75-4950-b519-7d9c63e8f5e1.png">

- [ ] **ログイン状態の場合でも、自身が出品した売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するよう修正しましょう**
自身が出品した"売却済み"商品の商品情報編集ページへ遷移できてしまいます。


- [ ] **商品一覧、商品購入ページにて、商品出品時に登録した情報のうち、「画像・商品名・価格・配送料の負担」の4つの情報が、見本アプリと同様の形で表示されるよう修正しましょう**
「配送料の負担」ではなく「発送までの日数」が表示されています。
<img width="311" alt="スクリーンショット_2021-11-14_15_41_01" src="https://user-images.githubusercontent.com/54050089/141670506-cf5dfe51-e6ba-4788-a10c-3b3362313836.png">
<img width="898" alt="スクリーンショット_2021-11-14_15_54_26" src="https://user-images.githubusercontent.com/54050089/141670807-6e0a41b6-1de3-41c0-9459-f2bd1f4e512b.png">



修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
@chiharukakimoto さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！　**LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**

**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/141674206-376f8393-aa58-470a-bfb6-1be2c3c11a26.png)
